Models/Category.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ShagoWeb.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }


        [Required]
        [MaxLength(30)]
        public String Name { get; set; }


        [Range(1,10)]
        public int DisplayOrder { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace ShagoWeb.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;

namespace ShagoWeb.Controllers
{
    public class CarController : Controller
    {
        public IActionResult Drive()
        {
            return View();
        }
    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ShagoWeb.Data;
using ShagoWeb.Models;
using System.Reflection.Metadata.Ecma335;

namespace ShagoWeb.Controllers
{
	public class CategoryController : Controller
	{
		private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
			_db = db;
        }
        public IActionResult Index()
		{
			List<Category> objCategoryList = _db.Categories.ToList();
			return View(objCategoryList);
		}
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category obj) 
        {
            if(ModelState.IsValid) 
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Category Created!";
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            Category categoryFromDb = _db.Categories.Find(id);

            if(categoryFromDb  == null) 
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Category Edited!";
                return RedirectToAction("Index");
            }
            return View();
        }



		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			Category categoryFromDb = _db.Categories.Find(id);

			if (categoryFromDb == null)
			{
				return NotFound();
			}
			return View(categoryFromDb);
		}

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)

        {
            Category obj = _db.Categories.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            else
            {
                _db.Categories.Remove(obj);
                _db.SaveChanges();
                TempData["success"] = "Category Deleted!";
                return RedirectToAction("Index");
            }
        }
		
		}
	}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ShagoWeb.Models;
using System.Diagnostics;

namespace ShagoWeb.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();

		}


		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Views/Car/Index.cshtml
<h1>Car is  Diving</h1>

Views/Car/drive.cshtml
        <h1>Car is Driving</h1>
   

Views/Category/Create.cshtml
@model Category;

<form method="post">
	<input asp-for"Id" hidden />

	<div class="border p-3 mt-3 border-black">
		<div class="row pb-2">
			<h1 class="text-dark">Create Category</h1>
		</div>

		<div class="mb-2">
			<label class="text-dark">Category Name</label>
			<input asp-for="Name" class="form-control"></>
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>


		<div class="mb-2">
			<label class="text-dark ">DisplayOrder</label>
			<input asp-for="DisplayOrder" class="form-control"></>
			<span asp-validation-for="DisplayOrder" class="text-danger"></span>
		</div>

		<div class="row">
			<dev class="col-6">
				<button type="submit" class="btn btn-dark" style="width:150px">Create</button>
			</dev>

			<dev class="col-6">
				<a asp-controller="Category" asp-action="Index" class="btn btn-outline-dark" style="width:150px" >Back</a>
			</dev>


		</div>

	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial"></partial>
	}
}

Views/Category/Delete.cshtml
@model Category;

<form method="post">
	<input asp-for"Id" hidden />
	<div class="border p-3 mt-3 border-black">
		<div class="row pb-2">
			<h1 class="text-dark">Delete Category</h1>
		</div>

		<div class="mb-2">
			<label class="text-dark">Category Name</label>
			<input asp-for="Name" class="form-control" disabled />
		
		</div>

		<div class="mb-2">
			<label class="text-dark ">DisplayOrder</label>
			<input asp-for="DisplayOrder" class="form-control" disabled/>
			
		</div>

		<div class="row">
			<dev class="col-6">
				<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
			</dev>

			<dev class="col-6">
				<a asp-controller="Category" asp-action="Index" class="btn btn-outline-dark" style="width:150px">Back</a>
			</dev>
		</div>
	</div>
</form>

Views/Category/Edit.cshtml
@model Category;

<form method="post">
	<input asp-for"Id" hidden />
	<div class="border p-3 mt-3 border-black">
		<div class="row pb-2">
			<h1 class="text-dark">Edit Category</h1>
		</div>

		<div class="mb-2">
			<label class="text-dark">Category Name</label>
			<input asp-for="Name" class="form-control"></>
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>

		<div class="mb-2">
			<label class="text-dark ">Display Order</label>
			<input asp-for="DisplayOrder" class="form-control"></>
			<span asp-validation-for="DisplayOrder" class="text-danger"></span>
		</div>

		<div class="row">
			<dev class="col-6">
				<button type="submit" class="btn btn-dark" style="width:150px">Update</button>
			</dev>

			<dev class="col-6">
				<a asp-controller="Category" asp-action="Index" class="btn btn-outline-dark" style="width:150px">Back</a>
			</dev>
		</div>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial"></partial>
	}
}

Views/Category/Index.cshtml
@model List<Category>




<dev class="container">
    <dev class="row pt-4 pd-4">
           <dev class="col-6">
            <h2 class="text-dark">C A T E G O R Y <i class="bi bi-heart-fill"></i></h2>
           </dev>
    
    <div class="col-6 text-end">
        <a asp-controller="Category" asp-action="Create" class="btn btn-dark">
                <i class="bi bi-plus-circle "></i> Add New Category</a>
    </div>
    </dev>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Category List</title>
</head>
<body>
    
    <table class="table table-bordered table-striped" >
        <thead>
            <tr class="table-dark">
              
                <th>Category Name</th>
                <th>Display Order</th>
                <th>Action</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model.OrderBy(u => u.Id))
            {
               <tr class="table-light">
                    
                    <td>@obj.Name</td>
                    <td>@obj.DisplayOrder</td>

                    <td>
                        <div class = "w-75 btn-group" role="group">

                                <a asp-controller="Category" asp-action="Edit"  class="btn btn-dark mx-0" asp-route-id="@obj.Id">
                                        <i class="bi bi-pencil-square"></i> Edit</a>

                                <a asp-controller="Category" asp-action="Delete" class="btn btn-danger mx-0" asp-route-id="@obj.Id">
                                    <i class="bi bi-trash"></i> Delete</a>
                        </div>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</body>
</dev>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShagoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShagoWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShagoWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Drive">Car</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> 
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial Name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-center">
        <div class="container">
           Made with <i class="bi bi-heart-fill"></i> By DotnetShago
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}